# Generated by Django 4.2.7 on 2024-04-17 19:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_productimage_is_main"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="content_rich",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
