# Generated by Django 4.2.7 on 2024-04-17 19:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_product_content_rich"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="content_rich",
        ),
    ]
