# Generated by Django 4.2.7 on 2024-04-20 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productoptionvalue",
            name="option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.option"
            ),
        ),
    ]
